from tkinter import *
import Main
import dictionary_data
###Class Implementation for the rows / buttons is not complete, this code doesn't do anything yet.###
### Generation of objects via dictionary testing in tkinter test project####


class Row():
    # Row objects generated by items list dictionary.  Dictionary creates row name variable and passes a row number and corresponding dictionary key to the constructor
    # Each Row has the following attributes
    # row_number = this is the number of the row where this object is propagated
    # row_key = this is the value from the items list (e.g."Onions, etc") which can be passed to the callback function for each button
    # remove_button = contructs a Remove_Button object, passes the row_key to the consturctor for button callback
    # row_label = constructs a Label object, passes the row_key for label.display_text
    # add_button = contructs an Add_Button object, passes the row_key to the consturctor for button callback
    # qty_box = constructs a Qty_Box object, passes the row_key to the constructor for qty_box.insert() function
    # pr_box = constructs a Pr_Box object, passes the row_key to the constructor for Pr_box.insert() function
    # sbtl_box = constructs a Sbtl_Box object, passes the row_key to the constructor for Sbtl_box.insert() function

    # Refresher function needs to be modified for new classes, but the exact implementation needs trial and error


class Remove_Button():


class Label():


class Add_Button():


class Qty_Box():


class Pr_Box():


class Sbtl_Box():
